import Head from 'next/head'
import home from "../styles/Home.module.scss"
import {Htag} from "../components/Htag/Htag";
import {Button} from "../components/Button/Button";

export default function Home() {
    return (
        <>
            <Head>
                <title>Learn Next JS</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={home.Home}>
                <Htag bol={`true`}>Where T E S T</Htag>
                <Button>Button</Button>
            </div>
        </>
    )
}
